### ISSUE TITLE
Error when trying to run on Macbook pro or lab iMac

### ISSUE THREAD

**Issue by jgrandfield** [drebain/CSC305_GLSL_Lecture#2]
The error I get when trying to run example 5 on either my personal Macbook or the iMacs in lab 354 is: icg/external/eigen/include/Eigen/src/Core/CwiseNullaryOp.h:501: error: ambiguous conversion for functional-style cast from 'int' to 'Scalar' (aka 'Eigen::Matrix<unsigned char, 4, 1, 0, 4, 1>')
return setConstant(Scalar(0)); 

As far as I can tell Example 6 and 7 also do not render the bunny you include but 6 does render the much simpler bunny.obj we were given in our lab (7 renders a full black window every time I've tried). I have included the appropriate files from your data folder and copied the example cpp code from apps as you recommended into the working icg project we have been using in lab with Qt Creator

**Comment by drebain** [comment]
The only issue I was able to reproduce on the macbook I have access to is the black screen for example 7, which is caused by the macos opengl implementaion not liking the use of textureOffset in a loop. You can get around this by removing the effect shader from the final fsquad->draw_texture call, which should allow you to just see the framebuffer "mirror" effect. If you want to do a convolutional effect and have it run on the lab macs, you could just manually unroll the for-loop.

Regarding example 5, that looks like it may be an issue with the texture loading code in OpenGP, so you should ask Arthur about it as I believe he may have modified that code for the version of OpenGP he is using in the labs.

The bunny mesh in this repo works on the mac that I have so that is a mystery to me. The only idea I have is that you could try using the OpenGP folder in this repo to replace the one in your icg folder in case there are differences between them that I am not aware of.

**Comment by drebain** [comment]
I was able to figure out the bug causing the issue with example 5 and I have created a pull request on Arthur's OpenGP fork with a fix, however it turns out that the icg repository is not configured to use the png loading library (libpng) that OpenGP requires for the imread function to work.

You may either use the png loading code from Arthur that is in the icg repo, or you can try to alter the icg cmake configuration to link your code with libpng.
